LakeWayCottages/LakeWayCottages/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from basic_app.views import index
from django.contrib.auth.views import PasswordChangeView,PasswordResetDoneView,PasswordResetView,PasswordResetConfirmView,PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app/',include('basic_app.urls')),
    path('reset_password',PasswordResetView.as_view(template_name='password_resetting/password_reset_form.html'),name='reset_password'),
    path('password_reset_done',PasswordResetDoneView.as_view(template_name='password_resetting/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='password_resetting/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteView.as_view(template_name='password_resetting/password_reset_complete.html'),name='password_reset_complete')
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LakeWayCottages/basic_app/urls.py
from django.urls import path
from basic_app import views
app_name='basic_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('createFeature/',views.createFeature.as_view(),name='createFeature'),
    path('updateFeature/<int:pk>/',views.updateFeature.as_view(),name='updateFeature'),
    path('deleteFeature/<int:pk>/', views.deleteFeature.as_view(), name='deleteFeature'),
    path('createApartment/',views.createApartment.as_view(),name='createApartment'),
    path('updateApartment/<int:pk>/',views.updateApartment.as_view(),name='updateApartment'),
    path('deleteApartment/<int:pk>/', views.deleteApartment.as_view(), name='deleteApartment'),
    path('email/',views.contactMail,name='mail'),
    path('login/',views.userLogin,name='login'),
    path('logout/',views.user_logout,name='logout')
]

LakeWayCottages/basic_app/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class features(models.Model):
    image=models.ImageField(upload_to='images',blank=True)
    desc=models.TextField(max_length=250)

    def get_absolute_url(self):
        return reverse("index")


class apartmentType(models.Model):
    ApartmentTitle=models.CharField(max_length=15)
    image=models.ImageField(upload_to='images',blank=True)
    desc=models.TextField(max_length=256)

    def get_absolute_url(self):
        return reverse("index")

LakeWayCottages/basic_app/views.py
from django.conf import settings
from django.core.checks import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from basic_app import models
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login,logout


# Create your views here.

def index(request):
    feature = models.features.objects.all()
    apartment = models.apartmentType.objects.all()
    return render(request, 'basic_app/index.html', {'obj': feature, 'apartment': apartment})


class createFeature(CreateView):
    fields = ('image', 'desc')
    model = models.features


class updateFeature(UpdateView):
    fields = ('image', 'desc')
    model = models.features


class deleteFeature(DeleteView):
    context_object_name = 'feature'
    model = models.features
    success_url = reverse_lazy("basic_app:index")


class createApartment(CreateView):
    fields = ('image','ApartmentTitle', 'desc')
    model = models.apartmentType


class updateApartment(UpdateView):
    fields = ('image', 'desc')
    model = models.apartmentType


class deleteApartment(DeleteView):
    context_object_name = 'apartment'
    model = models.apartmentType
    success_url = reverse_lazy("basic_app:index")


def contactMail(request):
    check = False
    if request.method == 'POST':
        username = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        print(username)
        print(email)
        print(message)
        msg = "Name : " + username + "\n" + "Email : " + email + "\n" + "Message : " + message
        send_mail(
            subject,
            msg,
            settings.EMAIL_HOST_USER,
            ['mwajihrehman@gmail.com'],
            fail_silently=False,
        )


def userLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return HttpResponse("Wroong details")

    else:
        return render(request, 'basic_app/login.html')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

LakeWayCottages/templates/basic_app/apartmenttype_confirm_delete.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}
<div style="background-image: url({% static 'wood.jpg' %});">
        <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<form method="POST" class="d-flex justify-content-center" >

        {%csrf_token%}
    <div class="jumbotron " >
    <h1 class="d-flex justify-content-center">Delete {{apartment.ApartmentTitle}} ??</h1>
    <input type="submit" class="btn btn-danger" value="Delete">
    <p><a class="btn btn-warning" href="{%url 'basic_app:index'%}">Cancel</a></p>
    </div>
</form>
    </div>
{%endblock%}

LakeWayCottages/templates/basic_app/apartmenttype_form.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}
<div class="parallax" style="background-image: url({% static 'wood.jpg' %});">
        <br>
<br>
<br>
<br>
<br>

    <form method="POST" enctype="multipart/form-data" class="d-flex justify-content-center">

    {%csrf_token%}
    <div class="jumbotron ">
           <h1 class="d-flex justify-content-center">
        {%if not form.instance.pk%}
        Create New Apartment
        {%else%}
        Edit Apartment
        {%endif%}
    </h1>
    {{form.as_p}}
        <div class="d-flex justify-content-end"><input type="submit" class="btn btn-success" value="Submit"></div>
    </div>

</form>
</div>
{%endblock%}

LakeWayCottages/templates/basic_app/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{%static "logo.jpg" %}" rel="icon">
  <link href="/media/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/media/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/media/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="/media/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/media/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="/media/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/media/vendor/owl.carousel//media/owl.carousel.min.css" rel="stylesheet">
  <link href="/media/vendor/aos/aos.css" rel="stylesheet">

  <link href="/media/css/style.css" rel="stylesheet">

  <style>
#flash {
  width: 100px;
  height: 100px;
  color: red;
  position: relative;
  animation-name: example;
  animation-duration: 1s;
  animation-iteration-count: 150;
  animation-direction: alternate;
}

@keyframes example {
  0%   {color:red;}
  25%  {color:yellow;}
  50%  {color:blue;}
  75%  {color:green;}
  100% {color:red;}
}

.parallax {
  /* The image used */
  background-image: url("img_parallax.jpg");

  /* Set a specific height */
  min-height: 500px;

  /* Create the parallax scrolling effect */
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}


</style>


</head>

 <header id="header" class="fixed-top ">
    <div class="container-fluid d-flex align-items-center justify-content-between">
       <a href="index.html" class="logo"><img src="{%static "logo.jpg"%}" alt="" height=120px width=90px class="img-fluid"></a>

      <h1 class="logo"><a href="">LakeWay Cottages</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a class="nav-link js-scroll-trigger" href="{%url 'index'%}">Home</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>

          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
          {% if request.user.is_authenticated %}
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'basic_app:createFeature'%}">Create Feature</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'basic_app:createApartment'%}">Create Apartment</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'basic_app:logout'%}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'basic_app:login'%}">Login</a></li>
            {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

      <a  href="#about" class="get-started-btn scrollto" style="background:#76922b">Get Started</a>
         <a href="https://5gemporium.com/" class="logo"><img  height=120px width=90px  src="{%static "5G Group of Companies.jpg"%}" alt=""class="img-fluid"></a>

    </div>
  </header><!-- End Header -->

    {%block body_block%}
    {%endblock%}


  <footer id="footer">
    <div class="footer-top " style="background:#76922b">
      <div class="container">
        <div class="row">
        </div>
        <div class="d-flex justify-content-around">
          <a href="index.html" class="logo"><img src="{%static "logo.jpg"%}" alt="" height=120px width=130px class="img-fluid"></a>
      <a href="https://5gemporium.com/" class="logo "><img  height=120px width=130px  src="{%static "5G Group of Companies.jpg"%}" alt=""class="img-fluid"></a>
      <a href="https://5gemporium.com/" class="logo "><img  height=150px width=210px  src="{%static "5G Properties.jpg"%}" alt=""class="img-fluid"></a>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>LakeWay Cottages</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/dewi-free-multi-purpose-html-template/ -->
        Designed by <a href="https://datatines.pythonanywhere.com/">DATA-TINES</a>
      </div>
    </div>
  </footer>

<script src="/media/vendor/jquery/jquery.min.js"></script>
  <script src="/media/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/media/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="/media/vendor/php-email-form/validate.js"></script>
  <script src="/media/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="/media/vendor/counterup/counterup.min.js"></script>
  <script src="/media/vendor/venobox/venobox.min.js"></script>
  <script src="/media/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="/media/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/media/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="/media/js/main.js"></script>
</body>
</html>

LakeWayCottages/templates/basic_app/features_confirm_delete.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}
<div style="background-image: url({% static 'wood.jpg' %});">
        <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<form method="POST" class="d-flex justify-content-center" >

        {%csrf_token%}
    <div class="jumbotron " >
    <h1 class="d-flex justify-content-center">Delete {{feature.desc}} ??</h1>
    <input type="submit" class="btn btn-danger" value="Delete">
    <p><a class="btn btn-warning" href="{%url 'basic_app:index'%}">Cancel</a></p>
    </div>
</form>
    </div>
{%endblock%}

LakeWayCottages/templates/basic_app/features_form.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}
<div class="parallax" style="background-image: url({% static 'wood.jpg' %});">
        <br>
<br>
<br>
<br>
<br>
    <form method="POST" enctype="multipart/form-data" class="d-flex justify-content-center">

    {%csrf_token%}
    <div class="jumbotron ">
           <h1 class="d-flex justify-content-center">
        {%if not form.instance.pk%}
        Create New Feature
        {%else%}
        Edit Feature
        {%endif%}
    </h1>
    {{form.as_p}}
        <div class="d-flex justify-content-end"><input type="submit" class="btn btn-success" value="Submit"></div>
    </div>

</form>
</div>
{%endblock%}

LakeWayCottages/templates/basic_app/index.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{%static "hero1.jpg"%}" height="700px" alt="First slide">
      <div class="carousel-caption">
        <h1 class="text-uppercase text-white font-weight-bold">In the Heart of Naran Valley</h1>
        <h3>Enjoy the epic view of Nature</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero3.jpeg"%}" height="700px" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero2.jpg"%}" height="700px" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static "hero4.jpeg"%}" height="700px" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<section id="about" class="about ">
      <div class="jumbotron container " style="background: linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(118,146,43,1) 100%, rgba(255,255,255,1) 100%)" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-6 video-box align-self-baseline" data-aos="zoom-in" data-aos-delay="100">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/OTEfbC94BoI?autoplay=1&showinfo=0&controls=0&start=5" frameborder="0" allow="autoplay;" allowfullscreen></iframe>
          </div>

          <div class="col-lg-6 pt-3 pt-lg-0 content">
            <h3>Something about LakeWay Cottages.</h3>
            <h4 class="font-italic">
              5G Group of Companies presents  Lakeway Cottages which is being constructed on 20.5 Kanal Land towards the Saif ul Mulook Lake in Naran, Pakistan.

            </h4>
            <ul>
              <li><i class="bx bx-check-double"></i>Located in a Main Naran valley of outstanding natural beauty.</li>
              <li><i class="bx bx-check-double"></i> Naran is the number one and top crowd catch traveling and touring HUB of Pakistan. Which is located in KPK East end and attracted the Punjab and Sindh public alongwith foreigners as well.</li>
              <li><i class="bx bx-check-double"></i>All the cottages have have river walks abounding in Mountain Valley. Just 10 minutes walk from Naran Bazar at Jheel Road.</li>
              <li><i class="bx bx-check-double"></i>All the cottages have have river walks abounding in Mountain Valley. Just 10 minutes walk from Naran Bazar at Jheel Road.</li>
            </ul>

          </div>

        </div>

      </div>
</section>
    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Benifits</h2>
          <p>What Should you Invest in us?</p>
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="200">
          <div class="col-md-6">
            <div class="icon-box">
              <i class="icofont-computer"></i>
              <h2><a href="#" id="flash">Best investment for rental income</a></h2>
            </div>
          </div>

          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-image"></i>
              <h2><a href="#" id="flash">Asset in tourism sector</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-settings"></i>
              <h2><a href="#" id="flash">Future best investment</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-earth"></i>
              <h2><a href="#" id="flash">long lasting asset</a></h2>
            </div>
          </div>
          <div class="col-md-6 mt-4 mt-md-0">
            <div class="icon-box">
              <i class="icofont-tasks-alt"></i>
              <h2><a href="#" id="flash">Asset & investment</a></h2>
            </div>
          </div>
        </div>

      </div>
    </section>


    <section id="portfolio" class="parallax portfolio" style="background-image: url({% static 'wood.jpg' %});">
      <div class="container " data-aos="fade-up">

        <div class="section-title">
          <h2 class="text-white">Features</h2>
          <p class="text-white">Check out our Features</p>
        </div>


        <div class="row portfolio-container " data-aos="fade-up" data-aos-delay="200">
    {%for f in obj%}
          <div class="col-xl-2 col-md-6 portfolio-item filter-app d-flex justify-content-center">
            <img src="/media/{{f.image}}" style="height=350px;width:350px" class="img-fluid" alt="">
            <div class="portfolio-info bg-success" >
              <h4 >{{f.desc}}</h4>
            </div>

          </div>

  {%endfor%}

        </div>
        {%if request.user.is_authenticated%}
          {%for f in obj%}
<div class="d-flex justify-content-around">
              <h4 class="text-white">{{f.desc}}</h4>
            <div class="container d-flex flex-row d-flex justify-content-center">
              <p><a class="btn btn-warning" href="{%url 'basic_app:updateFeature' pk=f.id%}">Edit Feature</a></p>
              <p><a class="btn btn-danger" href ="{%url 'basic_app:deleteFeature' pk=f.id%}">Delete Feature</a></p>
              </div>
  </div>
  {%endfor%}
        {%endif%}

      </div>
    </section>



  <section id="team" class="team section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Apartments</h2>
          <p>Check out our Apartment type and Division</p>
        </div>

        <div class="row d-flex justify-content-center">
        {%for a in apartment%}
          <div class="col-lg-4 col-md-6 ">
            <div class="member " data-aos="fade-up" data-aos-delay="100 ">
              <div class="pic"><img src="/media/{{a.image}}" height="350px" width="350px" class="img-fluid" alt=""></div>
              <div class="member-info" style=" background: linear-gradient(to top left, #ffffff 0%, #76922b 100%);">
                <h4>{{a.ApartmentTitle}}</h4>
                <span>{{a.desc}}</span>

              </div>
            </div>
            <div class="container d-flex flex-row ">
              <p><a class="btn btn-warning" href="{%url 'basic_app:updateApartment' pk=a.id%}">Edit Apartment</a></p>
              <p><a class="btn btn-danger" href ="{%url 'basic_app:deleteApartment' pk=a.id%}">Delete Apartment</a></p>
              </div>

          </div>

         {%endfor%}

        </div>

      </div>
    </section>
   <section id="contact" class="contact">
      <div class="container" data-aos="fade-up"">

    <div class=" section-title">
        <h2>Contact</h2>
        <p>Contact Us</p>
      </div>

      <div class="row">

        <div class="col-lg-6">

          <div class="row">
            <div class="col-md-12">
              <div class="info-box">
                <a href="https://www.google.com/maps/place/5G+Properties/@33.6700425,72.9971868,17z/data=!3m1!4b1!4m5!3m4!1s0x38df95f8b4b2f895:0xf88a1971f9e9fde5!8m2!3d33.6700381!4d72.9993755">
                <i class="bx bx-map" style="color:#76922b"></i>
                  </a>
                <h3>Our Address</h3>
                <p>Office No. 31, 2nd Floor, Al Hameed Plaza, G-11 Markaz, Islamabad</p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box mt-4">
                <a class="btn-floating btn-gplus mx-1" href="mailto:hasanfmradio@gmail.com">
                <i class="bx bx-envelope" style="color:#76922b"></i>
                </a>
                <h3>Email Us</h3>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box mt-4">
                <a class="btn-floating btn-gplus mx-1" href="tel:+923337777703">
                <i class="bx bx-phone-call" style="color:#76922b"></i>
                </a>
                <h3>Call Us</h3>
              </div>
            </div>
          </div>

        </div>

        <div class="col-lg-6 mt-4 mt-lg-0">
          <form  action="{%url 'basic_app:mail'%}"  method="POST"  class="php-email-form">
            <div class="form-row">
              <div class="col-md-5 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validate"></div>
              </div>
              <div class="col-md-5 form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validate"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validate"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validate"></div>
            </div>
          <div class="mb-3">
               <div class="loading">Your message has been sent. Thank you!</div>
              <div class="error-message"></div>

            </div>
            <div class="text-center"><a href="{%url 'basic_app:index'%}"><button id="btn" type="submit" style="background-color:#76922b">Send Message</button></a></div>
            {%csrf_token%}

          </form>

        </div>

      </div>

      </div>
    </section>




</script>
{%endblock%}

LakeWayCottages/templates/basic_app/login.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
{%load static%}
<br>
<br>
<br>
<br>
<br>
<br>

	<body class=" container" style="background:#76922b">
		<div class="jumbotron bg-dark d-flex justify-content-around h-100 ">

				<div class="d-flex justify-content-center form_container">
					<form action="{%url 'basic_app:login'%} " method="POST" class="text-white">

						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user">Username</i></span>
							</div>
							<input type="text" name="username"  class="form-control input_user " value="" placeholder="username">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key">Password</i></span>
							</div>
							<input type="password" name="password" class="form-control input_pass" value="" placeholder="password">
						</div>
						<div class="form-group">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input" id="customControlInline">
								<label class="custom-control-label" for="customControlInline">Remember me</label>
							</div>
							<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<a href="{%url 'reset_password'%}" class="text-white">Forgot your password?</a>
					</div>
				</div>
						</div>
							<div class="d-flex justify-content-center mt-3 login_container">
				 	<input type="submit"   class="btn btn-primary" value="Login">
				   </div>
				    {%csrf_token%}
					</form>
				</div>


			</div>
		</body>


{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_complete.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>
    <div class="alert alert-info" role="alert">
        <p class="d-flex justify-content-center">Congratulations your password has been succesfully changed</p>
    </div>
        <a class="d-flex justify-content-center btn btn-primary" href="{%url 'basic_app:login'%}" >Sign in!</a>


<br>
</body>
{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_confirm.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>
<div class="jumbotron">
    <form method="POST">

{{form}}
        <div class="container">
  <div class="row">
    <div class="col text-center">
      <input type="submit"   class="btn btn-primary" value="Reset Password">
    </div>
  </div>
</div>
        {%csrf_token%}
</form>
</div>
<br>
</body>
{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_done.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>
    <div class="alert alert-info" role="alert">
        <p class="d-flex justify-content-center">A link has been sent to your emails with password resetting settings</p>
    </div>

<br>
</body>

{%endblock%}

LakeWayCottages/templates/password_resetting/password_reset_form.html
{% extends 'basic_app/base.html'%}
{%block body_block%}
<body style="background:#76922b">
<br>
<br>
<br>
<br>
<br>
<br>

<div class="jumbotron d-flex justify-content-around ">
    <h1 class="text-secondary">*Please enter the email that you gave in Registeration form</h1>
    <form method="POST">

        <div class="container">
  <div class="row">
      {{form}}

    <div class="col text-center">
        <br>
      <input type="submit"   class="btn btn-primary" value="Reset Password">
    </div>
  </div>
</div>
        {%csrf_token%}
</form>
</div>
<br>
</body>
{%endblock%}